export type SolanaRpcTag =
  | "default"
  | "history"
  | "test"
  | "send"
  | "update"
  | "programUpdate"
  | "blockUpdate"
  | "slotUpdate"
  | "programAccounts"
  | "private"
  | "unlimited"
  | "batch"
  | "alchemy"
  | "helius"
  | "tokens"
  | "multipleAccounts"
  | "";
